---
title: "Similarity of introduced birds"
output: html_notebook
---

```{r}
source('../env.R')
```

# Load required data
```{r}
trait_data = read.csv(filename(TAXONOMY_OUTPUT_DIR, 'traits_ebird.csv')) %>% dplyr::select(ebird_species_name, beak_width, hwi, mass)
trait_data
```

```{r}
community_data = read.csv(filename(COMMUNITY_OUTPUT_DIR, 'communities_for_analysis.csv')) %>% 
  dplyr::select(city_id, city_name, ebird_species_name, origin, relative_abundance_proxy) %>% 
  left_join(trait_data, by = 'ebird_species_name')
community_data
```




```{r}
columbidae_tree = read.tree(filename(TAXONOMY_OUTPUT_DIR, 'phylogeny.tre'))
plot(columbidae_tree)
```

```{r}
realms = read_csv(filename(CITY_DATA_OUTPUT_DIR, 'realms.csv')) %>% mutate(city_id = factor(city_id))
```

# Find communities with introduced species
```{r}
urban_introduced_species = community_data %>% filter(origin == 'Introduced') %>% filter(relative_abundance_proxy > 0)
urban_introduced_species
```

```{r}
urban_native_species = community_data %>% filter(origin != 'Introduced') %>% filter(relative_abundance_proxy > 0)
urban_native_species
```

```{r}
regional_native_species = community_data %>% filter(origin != 'Introduced') %>% filter(relative_abundance_proxy == 0)
regional_native_species
```


# Find cities we can use to compare introduced species vs regional species
```{r}
city_names = function(df) {
  df %>% dplyr::select(city_id, city_name) %>% distinct()
}

cities_available_for_test = purrr::reduce(
  list(
    city_names(urban_introduced_species),
    city_names(urban_native_species),
    city_names(regional_native_species)
  ),
  dplyr::intersect
)
cities_available_for_test
```

# Look at creating required metrics for a single city
```{r}
test_city = cities_available_for_test$city_name[1]
```

## Distance to nearest species across functional traits
```{r}
native_traits = urban_native_species %>%
  filter(city_name == test_city)

introduced_traits = urban_introduced_species %>%
  filter(city_name == test_city)

regional_traits = regional_native_species %>%
  filter(city_name == test_city)

introduced_traits %>%
  rowwise() %>%
  mutate(
    min_dist_beak_width = min(abs(beak_width - native_traits$beak_width)),
    min_dist_mass       = min(abs(mass - native_traits$mass)),
    min_dist_hwi        = min(abs(hwi - native_traits$hwi))
  ) %>%
  ungroup()

regional_traits %>%
  rowwise() %>%
  mutate(
    min_dist_beak_width = min(abs(beak_width - native_traits$beak_width)),
    min_dist_mass       = min(abs(mass - native_traits$mass)),
    min_dist_hwi        = min(abs(hwi - native_traits$hwi))
  ) %>%
  ungroup()
```

## Distance to nearest species in phylogeny
```{r}
communities_matrix =  function(urban_community, comparison_community) {
  urban = str_replace(urban_community$ebird_species_name, ' ', '_')
  compare = str_replace(comparison_community$ebird_species_name, ' ', '_')
  
  spp = c(urban, compare)

  comm = matrix(
    0,
    nrow = 1 + length(compare),
    ncol = length(spp),
    dimnames = list(c("urban", compare), spp)
  )

  comm["urban", urban] = 1
  comm[cbind(compare, compare)] = 1
  comm
}

communities_matrix(native_traits, introduced_traits)
communities_matrix(native_traits, regional_traits)
```

```{r}
D = cophenetic(columbidae_tree)

min_phylo_distance = function(native_traits, compare_to_traits) {
  cdnt = picante::comdistnt(communities_matrix(native_traits, compare_to_traits), D)
  cdnt_m = as.matrix(cdnt)
  
  
  tibble(species = str_replace(compare_to_traits$ebird_species_name, ' ', '_')) %>%
      mutate(
        ebird_species_name = str_replace(species, '_', ' '),
        min_phylo_dist = cdnt_m[species, "urban"]
      ) %>% 
    dplyr::select(-species)
}

min_phylo_distance(native_traits, introduced_traits)
min_phylo_distance(native_traits, regional_traits)
```

# Create all metrics
```{r}
min_trait_distances = function(given_city_id) {
  native = urban_native_species %>%
    filter(city_id == given_city_id)
  
  introduced = urban_introduced_species %>%
    filter(city_id == given_city_id)
  
  regional = regional_native_species %>%
    filter(city_id == given_city_id)
  
  rbind(
    introduced %>%
      rowwise() %>%
      mutate(
        min_dist_beak_width = min(abs(beak_width - native$beak_width)),
        min_dist_mass       = min(abs(mass - native$mass)),
        min_dist_hwi        = min(abs(hwi - native$hwi))
      ) %>%
      ungroup() %>%
      left_join(min_phylo_distance(native, introduced)) %>%
      mutate(type = 'Introduced')
    ,
    regional %>%
      rowwise() %>%
      mutate(
        min_dist_beak_width = min(abs(beak_width - native$beak_width)),
        min_dist_mass       = min(abs(mass - native$mass)),
        min_dist_hwi        = min(abs(hwi - native$hwi))
      ) %>%
      ungroup() %>%
      left_join(min_phylo_distance(native, regional)) %>%
      mutate(type = 'Available')
  ) %>%
  dplyr::select(city_id, city_name, ebird_species_name, relative_abundance_proxy, type, min_dist_beak_width, min_dist_mass, min_dist_hwi, min_phylo_dist)
}

min_trait_distances(cities_available_for_test$city_id[1])
```

```{r}
result_df = data.frame()

for (i in 1:nrow(cities_available_for_test)) {
  test_city_id = cities_available_for_test$city_id[i]
  result_df = rbind(result_df, min_trait_distances(test_city_id))
}

result_df = result_df %>% mutate(type = as.factor(type), city_id = factor(city_id)) %>% left_join(realms, by = 'city_id')
result_df
```

```{r}
introduced_result = result_df[result_df$type == 'Introduced',]
introduced_result
```


```{r}
lme4::lmer(relative_abundance_proxy ~ min_dist_beak_width + (1 | city_id), introduced_result)
```


