---
title: "Find spatial sampling coverage for cities, along with spatial distribution of pigeons in cities"
output: html_notebook
bibliography: ../ref.bib 
---

```{r}
source('../env.R')
```

```{r}
RADIUS_FROM_CHECKLIST_CENTRE_FOR_SPATIAL_COVERAGE_M = 500
METRE_BASED_CRS = "+proj=utm +zone=42N +datum=WGS84 +units=m"
```

## Find area of each city
```{r}
initial_city_selection = st_read(filename(mkdir(GEO_WORKING_OUTPUT_DIR, 'cities'), 'initial_selection.shp'))
initial_city_selection_m = st_transform(initial_city_selection, METRE_BASED_CRS)
```

```{r}
city_total_areas = initial_city_selection_m %>% mutate(area_metres = st_area(geometry)) %>% data.frame() %>% dplyr::select(city_id, city_name, area_metres)
city_total_areas
```

## Find area covered by all checklists within city
```{r}
urban_checklists = read_csv(filename(EBIRD_WORKING_OUTPUT_DIR, 'urban_checklists.csv'))
head(urban_checklists)
```

```{r, warning=FALSE}
city_total_areas$surveyed_area = NA

for (selected_city_id in city_total_areas$city_id) {
  checklist_locations = urban_checklists %>% 
    filter(city_id == selected_city_id) %>% 
    dplyr::select(lat, long) %>% 
    distinct()
  
  if (nrow(checklist_locations) > 0) {
    city_polygon = initial_city_selection_m[initial_city_selection_m$city_id == selected_city_id,]
    
    checklists_sf = st_as_sf(checklist_locations, coords = c("long", "lat"))
    st_crs(checklists_sf) = 4326
    
    city_total_areas$surveyed_area[city_total_areas$city_id == selected_city_id] = checklists_sf %>%
      st_transform(METRE_BASED_CRS) %>%
      st_buffer(RADIUS_FROM_CHECKLIST_CENTRE_FOR_SPATIAL_COVERAGE_M) %>%
      st_union() %>%
      st_intersection(st_buffer(city_polygon, 0)) %>%
      st_area()
  } else {
    city_total_areas$surveyed_area[city_total_areas$city_id == selected_city_id] = 0
  }
}

city_total_areas$percentaged_surveyed = city_total_areas$surveyed_area * 100 / city_total_areas$area_metres
city_total_areas
```


## Find area each each city each pigeon is found
```{r}
pools = read_csv(filename(COMMUNITY_OUTPUT_DIR, 'jetz_all_recorded_species.csv'))
head(pools)
```

```{r}
columbidae_checklists = read_csv(filename(EBIRD_WORKING_OUTPUT_DIR, 'urban_columbidae.csv'))
nrow(columbidae_checklists)
head(columbidae_checklists)
```

```{r}
taxonomic_mapping = read_csv(filename(TAXONOMY_OUTPUT_DIR, 'taxonomy_mapping.csv'))
ebird_to_jetz_mapping = unique(taxonomic_mapping[,c('ebird_species_fullname', 'jetz_species_name')])
ebird_to_jetz_mapping
```

```{r}
columbidae_checklists_jetz = columbidae_checklists %>% left_join(ebird_to_jetz_mapping, by = c('species_name' = 'ebird_species_fullname')) %>% dplyr::select(checklist_id, jetz_species_name, city_id)
nrow(columbidae_checklists_jetz)
columbidae_checklists_jetz_distinct = distinct(columbidae_checklists_jetz)
head(columbidae_checklists_jetz_distinct)
```

```{r}
pools$area_found = NA

row = 2
for (row in 1:nrow(pools)) {
  selected_city_id = pools[row, c('city_id')]
  selected_species = pools[row, c('jetz_species_name')]
  
  checklists = columbidae_checklists_jetz_distinct %>% 
    filter(city_id == as.integer(selected_city_id)) %>% filter(jetz_species_name %in% c(selected_species)) %>% 
    dplyr::select(checklist_id)
  
  checklist_locations = urban_checklists %>% 
    filter(checklist_id %in% checklists$checklist_id) %>% 
    dplyr::select(lat, long) %>% 
    distinct()
  
  if (nrow(checklist_locations) > 0) {
    city_polygon = initial_city_selection_m[initial_city_selection_m$city_id == as.integer(selected_city_id),]
    
    checklists_sf = st_as_sf(checklist_locations, coords = c("long", "lat"))
    st_crs(checklists_sf) = 4326
    
    pools$area_found[row] = checklists_sf %>%
      st_transform(METRE_BASED_CRS) %>%
      st_buffer(RADIUS_FROM_CHECKLIST_CENTRE_FOR_SPATIAL_COVERAGE_M) %>%
      st_union() %>%
      st_intersection(st_buffer(city_polygon, 0)) %>%
      st_area()
  } else {
    pools$area_found[row] = 0
  }
}
```

```{r}
write_csv(pools, filename(EBIRD_WORKING_OUTPUT_DIR, 'area_found_within_city.csv'))
```

## Pull all data together
```{r}
nrow(pools)
pools_city_data = pools %>% 
  left_join(city_total_areas) %>% 
  rename(
    total_city_area_m2='area_metres', 
    total_city_area_surveyed_m2='surveyed_area', 
    total_presence_area_m2='area_found', 
    percentage_total_city_area_surveyed='percentaged_surveyed') %>%
  mutate(
    percentage_total_city_area_surveyed = as.integer(percentage_total_city_area_surveyed), 
    total_city_area_m2 = as.numeric(total_city_area_m2)) %>%  
  mutate(across(where(is.numeric), round, 2))

nrow(pools_city_data)
```


```{r}
pools_city_data$percentage_surveyed_area = pools_city_data$total_presence_area_m2 * 100 / pools_city_data$total_city_area_surveyed_m2

pools_city_data = pools_city_data %>% 
  dplyr::select(
    city_id, 
    city_name, 
    total_city_checklists, 
    total_city_locations, 
    total_city_effort, 
    total_city_area_m2, 
    total_city_area_surveyed_m2, 
    percentage_total_city_area_surveyed, 
    jetz_species_name, 
    percentage_checklists, 
    percentage_locations, 
    percentage_effort, 
    percentage_surveyed_area, 
    seasonal, 
    presence, 
    origin) %>% 
  data.frame()
pools_city_data
```

```{r}
write_csv(pools_city_data, filename(COMMUNITY_OUTPUT_DIR, 'jetz_all_recorded_species_with_spatial_data.csv'))
```

## Compare spatial metric to checklists

```{r}
ggplot(distinct(pools_city_data[,c('total_city_checklists', 'total_city_area_surveyed_m2')]), aes(x = total_city_checklists, y = total_city_area_surveyed_m2)) +
  geom_point() + geom_smooth()
```

```{r}
length(unique(pools_city_data$city_id[pools_city_data$percentage_total_city_area_surveyed > 20]))
```

```{r}
ggplot(pools_city_data[pools_city_data$percentage_total_city_area_surveyed > 20,], aes(x = percentage_checklists, y = percentage_surveyed_area)) +
  geom_point() + geom_smooth()
```


