---
title: "Find spatial sampling coverage for cities, along with spatial distribution of pigeons in cities"
output: html_notebook
bibliography: ../ref.bib 
---

```{r}
source('../env.R')
```

```{r}
RADIUS_FROM_CHECKLIST_CENTRE_FOR_SPATIAL_COVERAGE_M = 500
METRE_BASED_CRS = "+proj=utm +zone=42N +datum=WGS84 +units=m"
```

## Find area of each city
```{r}
initial_city_selection = st_read(filename(mkdir(GEO_WORKING_OUTPUT_DIR, 'cities'), 'initial_selection.shp'))
initial_city_selection_m = st_transform(initial_city_selection, METRE_BASED_CRS)
```
```{r}
city_total_areas = initial_city_selection_m %>% mutate(area_metres = st_area(geometry)) %>% data.frame() %>% dplyr::select(city_id, city_name, area_metres)
city_total_areas
```

## Find area covered by all checklists within city
```{r}
urban_checklists = read_csv(filename(EBIRD_WORKING_OUTPUT_DIR, 'urban_checklists.csv'))
head(urban_checklists)
```

```{r, warning=FALSE}
sf::sf_use_s2(FALSE)
city_total_areas$surveyed_area = NA

for (selected_city_id in city_total_areas$city_id) {
  checklist_locations = urban_checklists %>% 
    filter(city_id == selected_city_id) %>% 
    dplyr::select(lat, long) %>% 
    distinct()
  
  if (nrow(checklist_locations) > 0) {
    city_polygon = initial_city_selection_m[initial_city_selection_m$city_id == selected_city_id,]
    
    buffered_checklists %>% mutate(area_metres = st_area(geometry))
    
    checklists_sf = st_as_sf(checklist_locations, coords = c("long", "lat"))
    st_crs(checklists_sf) = 4326
    
    city_total_areas$surveyed_area[city_total_areas$city_id == selected_city_id] = checklists_sf %>%
      st_transform(METRE_BASED_CRS) %>%
      st_buffer(RADIUS_FROM_CHECKLIST_CENTRE_FOR_SPATIAL_COVERAGE_M) %>%
      st_union() %>%
      st_intersection(st_buffer(city_polygon, 0)) %>%
      st_area()
  } else {
    city_total_areas$surveyed_area[city_total_areas$city_id == selected_city_id] = 0
  }
}

city_total_areas$percentaged_surveyed = city_total_areas$surveyed_area * 100 / city_total_areas$area_metres
city_total_areas
```


## Find area each each city each pigeon is found
